### ISSUE TITLE
Recognition via video stream or playback

### ISSUE THREAD

**Issue by fakhrizulkifli** [marcbelmont/deep-license-plate-recognition#1]
It would be great to have an API for license plate recognition from live video feed or a recorded MP4 formatted.

**Comment by marcbelmont** [comment]
@fakhrizulkifli thanks for your suggestion. That's a great idea.

Do you have example videos/video feeds I could use for testing?

**Comment by fakhrizulkifli** [comment]
I cannot find any better sources than a simple Youtube query such as [this](https://www.youtube.com/watch?v=0CiJdOHawGM) but i think a video of license plate images should work too.

**Comment by marcbelmont** [comment]
That's great thanks. It will be good enough for now.
