### ISSUE TITLE
Django CSFR Error

### ISSUE THREAD

**Issue by MrCybertux** [marcbelmont/deep-license-plate-recognition#124]
**Describe the bug**
After setting up ParkPow behind a reverse Proxy all request going through the Proxy are getting a CSFR error

**To Reproduce**
1. Setup ParkPow with the Provided Docker file behind a Nignx Reverse Proxy for TLS
2. Connect via Revers proxy and try to login
3. See error Page with the Error 403  Forbidden (Origin checking failed - null does not match any trusted origins.)

**Expected behavior**
Have ParkPow available over TLS

**Desktop (please complete the following information):**
 - OS: Linux & Windows
 - Version: Linux 6.1.0-1parrot1-amd64 & Windows 11 22H2
 - Hardware: HP Elitebook & Lenovo Thinkpad

**Additional context**
Log entries

`2023-05-23 13:39:55 [WARNING] [/opt/pysetup/.venv/lib/python3.11/site-packages/django/utils/log.py:241]: Forbidden (Origin checking failed - null does not match any trusted origins.): /accounts/login/`

` () {72 vars in 1485 bytes} [Tue May 23 13:39:55 2023] POST /accounts/login/ => generated 1019 bytes in 3 msecs (HTTP/1.1 403) 7 headers in 229 bytes (1 switches on core 2)
`

**Comment by ttayson** [comment]
@MrCybertux is this a new installation? or did you already use it normally? 

we are checking the situation to simulate the problem based on your information

**Comment by MrCybertux** [comment]
> @MrCybertux is this a new installation? or did you already use it normally?
> 
> we are checking the situation to simulate the problem based on your information

It is new we finalized the setup today

**Comment by koteakh1** [comment]
A few questions:

1. Which browser are you using?
2. You are running into this issue when trying to log in (making a POST request). What happens when you simply load the login page? Does the page load over HTTP or HTTPS?
3. Are you changing origin and referrer headers via nginx?

**Comment by koteakh1** [comment]
`no-referrer` will definitely cause this issue. There could be other reasons too but let's start by replacing `no-referrer`. `X-Content-Type-Options` does not matter.

**Comment by ttayson** [comment]
@MrCybertux I was able to reproduce your problem and configure it to work properly, you need to add the X-Forwarded-Proto header to the configuration file in Nginx.

I am trying with pure Nginx, in my case it was only necessary to add the **proxy_set_header X-Forwarded-Proto $scheme** to the configuration file.

Please test and tell us if it worked correctly

![image](https://github.com/parkpow/deep-license-plate-recognition/assets/40831050/3261425d-fe7a-434c-81e1-59330eb894e2)
