### ISSUE TITLE
Other Country

### ISSUE THREAD

**Issue by alucard079** [marcbelmont/deep-license-plate-recognition#2]
Will it work for the philippine plate country?

Thanks in advance for your reply.

**Comment by marcbelmont** [comment]
It should work. Can you point me to examples of license plates from the
Philippines?

**Comment by alucard079** [comment]
I can make it work, I am trying now the Live Stream from the Camera, But I'm having a problem with that. I already post my concern about that. I created some thread issue also here. 

But thanks for your reply, here's the sample image in our country 
![zjg944](https://user-images.githubusercontent.com/28977709/51720803-0e5c0c80-208a-11e9-937e-282037a665a1.jpg)


![beg851](https://user-images.githubusercontent.com/28977709/51720852-4b280380-208a-11e9-9306-d7a2bfb92d9a.jpg)

**Comment by MayankKashyap** [comment]
Hey I am from India,  and can you explain this project briefly, That would be easy for understand your project
