### ISSUE TITLE
How to reduce confidence threshold for lpr reading?

### ISSUE THREAD

**Issue by sriramcu** [marcbelmont/deep-license-plate-recognition#24]
Is it possible to get a license plate with a lower confidence value if no readings appear? Like I'm fine with an LPR reading with a score of 0.5, etc.

**Comment by marcbelmont** [comment]
Yes, this is possible. You can pass `config=dict(threshold_o=.5)` to `recognition_api`.

https://github.com/marcbelmont/deep-license-plate-recognition/blob/master/plate_recognition.py#L48
