### ISSUE TITLE
PlateRecognizer-Installer.exe detected as malware

### ISSUE THREAD

**Issue by crassia** [marcbelmont/deep-license-plate-recognition#50]
**Describe the bug**
The windows install file, downloaded from https://app.platerecognizer.com/static/installer/PlateRecognizer-Installer.exe, was detected as malware by Windows Defender.
![image](https://user-images.githubusercontent.com/7344709/108379468-8cbf1480-7238-11eb-84db-f474de221385.png)
VirusTotal checking that URL also flagged it as malware:
![image](https://user-images.githubusercontent.com/7344709/108379588-a9f3e300-7238-11eb-90e4-177319225958.png)

**To Reproduce**
Check your file with VirusTotal to see yourself.

**Comment by marcbelmont** [comment]
This issue is fixed in the latest version of the installer.
