### ISSUE TITLE
issue localhost port 8080: Connection refused

### ISSUE THREAD

**Issue by scizors** [marcbelmont/deep-license-plate-recognition#57]
Hi,
 I have docker installed in my arm macine. 
 `# uname -m
armv7l
`
 
 I am using raspberry pi docker image. If I run docker then,
 
`# docker run --rm -t -p 8080:8080 -v license:/license -e TOKEN=bc44e48030a5735cdd428e7a231dca19b3d33d03 -e LICENSE_KEY=xxxxx platerecognizer/alpr-raspberry-pi
PlateRecognizer v1.20.0
License Key: xxxxx
Usage since 2021-04-09: 106/2500 calls.
Loading...`

issue with connecting localhost:

`# curl -F 'upload=@/tmp/car.jpg' http://localhost:8080/v1/plate-reader/
curl: (7) Failed to connect to localhost port 8080: Connection refused

`

**Comment by danleyb2** [comment]
@scizors What is the output from `docker ps`

**Comment by scizors** [comment]
Hi @danleyb2 ,
 Thank you for fast reply
 
 ```
# docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
# docker image ls
REPOSITORY                          TAG       IMAGE ID       CREATED        SIZE
platerecognizer/alpr-raspberry-pi   latest    d3881dcc37b5   29 hours ago   1.31GB
```

**Comment by danleyb2** [comment]
@scizors I don't see PORTS column listed, So i don't think you ran the correct command, The output should be something of this sort
![2021-05-07_02-12](https://user-images.githubusercontent.com/9919961/117376457-d8996580-aed9-11eb-9a37-8c238fd45d46.png)

**Comment by scizors** [comment]
Yes you are right please find the command below which I used to run the docker 

```
# docker image ls
REPOSITORY                          TAG       IMAGE ID       CREATED        SIZE
platerecognizer/alpr-raspberry-pi   latest    d3881dcc37b5   47 hours ago   1.31GB
# docker run --rm -t -p 8080:8080 -v license:/license -e TOKEN=bc44e48030a5735cdd428e7a231dca19b3d33d03 -e LICENSE_KEY=xxxxxxxx platerecognizer/alpr-raspberry-pi
PlateRecognizer v1.20.0
Starting online registration
You have used 1/2 license(s).
License Key: xxxxxxxxx
Usage since 2021-04-12: 0/2500 calls.
Loading...
# docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```

**Comment by danleyb2** [comment]
@scizors Are you able to run a different service that listens on a PORT on the host like the hello-world container

**Comment by scizors** [comment]
Hi @danleyb2,
yes I van run other services and hallo-world:

`# docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (arm32v7)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/
`

**Comment by scizors** [comment]
Hi,
 Thank you for your reply I don't have browser I have only CLI -Command Line Interface and GUI , web browser is not available in my ARM device. 

Do you have any other alternative solution?
 
```
# docker run -d -p 8000:80 docker/getting-started
Unable to find image 'docker/getting-started:latest' locally
latest: Pulling from docker/getting-started
docker: no matching manifest for linux/arm/v7 in the manifest list entries.
See 'docker run --help'.
```

**Comment by danleyb2** [comment]
@scizors  You can try curl to the url or telnet. 
@marcbelmont is docker networking done differently on **arm** ? We are not able to get a service to publish a port

**Comment by marcbelmont** [comment]
I suspect the docker networking is not configured well on your machine. I would try adding `--network=host` to your docker run command. With that it will use the host's network directly.

**Comment by marcbelmont** [comment]
That parameter has to come before the image name. Try that instead:
`docker run --network=host --rm -t -p 8080:8080 -v license:/license -e TOKEN=bc44e48030a5735cdd428e7a231dca19b3d33d03 -e LICENSE_KEY=xxxxxx platerecognizer/alpr-raspberry-pi `

**Comment by scizors** [comment]
```
# docker run --network=host --rm -t -p 8080:8080 -v license:/license -e TOKEN=bc44e48030a5735cdd428e7a231dca19b3d33d03 -e LICENSE_KEY=xxxxx platerecognizer/alpr-raspberry-pi
WARNING: Published ports are discarded when using host network mode
PlateRecognizer v1.20.0
License Key: xxxxxx
Usage since 2021-04-12: 0/2500 calls.
Loading...
```
```
~# curl -o /tmp/car.jpg https://app.platerecognizer.com/static/demo.jpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  297k  100  297k    0     0   367k      0 --:--:-- --:--:-- --:--:--  367k
```


```
~# curl -F 'upload=@/tmp/car.jpg' http://localhost:8080/v1/plate-reader/
curl: (7) Failed to connect to localhost port 8080: Connection refused
```

**Comment by marcbelmont** [comment]
Is the container still running? Can you share the output of `docker ps` and `docker logs id_of_container`?
Are you able to open http://localhost:8080 or http://127.0.0.1:8080 in a web browser?

**Comment by scizors** [comment]
no the container is not running
```
# docker logs id_of_container
Error: No such container: id_of_container
# docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```

**Comment by marcbelmont** [comment]
This hardware is currently not supported.
