### ISSUE TITLE
Question on using regions properly via python

### ISSUE THREAD

**Issue by pliablepixels** [marcbelmont/deep-license-plate-recognition#6]
Hi, thanks for the library. 
From the curl examples, it looks like the regions should be specified as form POST data

Would this be the right way?

The API response (via python or curl) doesn't tell me if it actually used the regions, because even if I enter random characters in the region, it still proceeds to detect plates without any region feedback in the response, so I don't know if I am doing it right.

```python
payload = {'regions':['kr','us']}
# payload = {'regions':'crouchingtigerhiddendragon'} # this works as well
                response = requests.post(
                        'https://api.platerecognizer.com/v1/plate-reader/',
                        files=dict(upload=fp),
                        data=payload,
                        headers={'Authorization': 'Token ' + self.apikey})
```

Thanks

**Comment by marcbelmont** [comment]
Yes, this is the correct way. If you provide invalid regions, we silently skip them. 

I am working on a change to show that regions are actually being used.

**Comment by pliablepixels** [comment]
Sounds good thanks.
Would also be good if we could forcibly restrict regions if need be, in the input (might help in reducing wrong readings)
