### ISSUE TITLE
Incorrect total_calls (hardcoded to 2500)

### ISSUE THREAD

**Issue by pliablepixels** [marcbelmont/deep-license-plate-recognition#7]
**Describe the bug**
The `total_calls` parameter in `/statistics` seems to be hardcoded

**To Reproduce**
Invoke `'https://api.platerecognizer.com/v1/statistics/`

**Expected behavior**
`total_calls` should be the summation of all calls per month

**Observed behavior**
`total_calls` is hardcoded to 2500

**Image of vehicle**
N/A

**Additional context**
Example output (2 successive calls)

```
# call 1 to stats
Jul  5 11:48:04 homeserver detect:[2920][monitor_m8]: DEBUG [Plate Recognizer API usage stats: {"usage": {"month": 7, "calls": 100, "year": 2019}, "total_calls": 2500}]

# invoke ALPR api to detected

# call 2 to stats
Jul  5 11:49:34 homeserver detect:[2942][monitor_m8]: DEBUG [Plate Recognizer API usage stats: {"usage": {"month": 7, "calls": 101, "year": 2019}, "total_calls": 2500}]
```

**Comment by marcbelmont** [comment]
The value you are looking for is "usage"/"calls"

I have updated the doc to clarify how to read the return value: http://docs.platerecognizer.com/#statistics
