### ISSUE TITLE
What is the license for self hosted docker image

### ISSUE THREAD

**Issue by harshajayaweeraXHJ** [marcbelmont/deep-license-plate-recognition#9]
If i use the self hosted docker image do I still need an API key or can I use it for free. What is the licensing mechanism for docker image.

**Comment by marcbelmont** [comment]
If you use the docker image, you still need an API key. Pricing is based on
the number of lookups. More info at https://platerecognizer.com/pricing/

**Comment by harshajayaweeraXHJ** [comment]
Got it thanks. Do you have any open source and self hosted alternatives for free at the time

**Comment by marcbelmont** [comment]
Sorry, we don't.
